# Site settings
title: Jonathan Price
email: jon.price77@gmail.com
description: "TBA: What I enjoy doing front end wise"
colophon: "This site is created by Jonathan Price using Jekyll and Github pages."
baseurl: ""
url: "http://informa.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title.html
