# Site settings
title: Jonathan Price
role: Frontend Developer
email: jon.price77@gmail.com
description: "I am a frontend developer that enjoys playing with new technology and builds flexible web applications for businesses."
baseurl: ""
url: "http://informa.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title.html
